config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :create, :new ] do
    resources :doses, only: [ :create, :new]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  belongs_to :user

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :cocktail, :ingredient, uniqueness: { scope: [ :ingredient, :cocktail ] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cocktails
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
   params.require(:cocktail).permit(:name, :photo)
 end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = cocktail
    if @dose.save
      redirect_to cocktail_path(cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">

<h6><%= link_to 'Add a new cocktail', new_cocktail_path %></h6>

<div class="cards">
<% @cocktails.each do |cocktail| %>
  <div class="card-category p-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo.key %>)">
    <%= link_to cocktail.name, cocktail_path(cocktail) %><br>

  </div>
<% end %>

</div>
<%= link_to 'home', root_path %>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "New cocktail"%>
<% end %>

<%= link_to 'Back home',cocktails_path  %>

app/views/cocktails/show.html.erb
<div class="container">

<h2 class="text-center"><%= @cocktail.name %></h2>
<p><%= link_to 'add a dose', new_cocktail_dose_path(@cocktail) %></p>
<p><%= link_to 'go back', cocktails_path %></p>
<div class="d-flex justify-content-center">
<ul>
<%= cl_image_tag @cocktail.photo.key, height: 300, crop: :fill %>
<p>How to make a <%= @cocktail.name %>:</p>
<% @cocktail.doses.each do |dose| %>
  <li> <%= dose.description %> - <%= dose.ingredient.name %>
  <%= link_to 'x', dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link"  %>
  </li>
<% end %>
</ul>

</div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.submit "New dose"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to 'Enter', cocktails_path %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand", data: { turbolinks: false } do %>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to "My Profile", user_path(current_user)%>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
          <%=  link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<%= link_to 'home', root_path  %>

<% @user.cocktails.each do |cocktail| %>
<li><%= cocktail.name %>
<%= cocktail.doses.first.description %>
<%= cl_image_tag cocktail.photo.key, height: 150, width: 150 %></li>
<% end %>